export { BaseLogo, DashboardLogo } from "./logo";
export { Category } from "./category";
export { Chart } from "./chart";
export { Bell, BellOutline } from "./bell";
export { Ticket } from "./ticket";
export { Document } from "./document";
export { Calender } from "./calendar";
export { Settings } from "./settings";
export { Plus } from "./plus";
export { Close } from "./close";
export { Menu } from "./menu";
export { Discord, Github, Linkedin, Twitter } from "./socials";
export { Google } from "./google";
export { Apple } from "./apple";
export { Upload, UploadDashboardButton } from "./upload";
